/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * High-performance event bus for Node.js.
 *
 * Example usage:
 * ```typescript
 * import { Net } from '@ai2070/net';
 *
 * const bus = await Net.create({ numShards: 4 });
 *
 * // Fast sync ingestion (no async overhead)
 * bus.ingestRawSync('{"token": "hello", "index": 0}');
 *
 * // Or batch for maximum throughput
 * bus.ingestRawBatchSync(['{"a":1}', '{"a":2}']);
 *
 * // Poll events (async)
 * const response = await bus.poll({ limit: 100 });
 *
 * await bus.shutdown();
 * ```
 */
export declare class Net {
  /** Create a new Net event bus. */
  static create(options?: EventBusOptions | undefined | null): Promise<Net>
  /**
   * Pre-compute hash for an event buffer.
   *
   * Use this for events that will be ingested multiple times (e.g., templates).
   * The returned HashedEvent can be passed to pushHashed() to skip hash computation.
   */
  prehash(data: Buffer): HashedEvent
  /**
   * Ingest with a pre-computed hash (fastest single-event path).
   *
   * Pass the buffer and its pre-computed xxhash to skip hash computation.
   * Use xxhash3 on JS side for compatible hash values.
   */
  pushWithHash(data: Buffer, hash: bigint): boolean
  /**
   * Ingest raw bytes with zero-copy (fastest possible).
   *
   * Accepts a Buffer directly from JS - no string conversion overhead.
   * Returns nothing for maximum speed.
   */
  push(data: Buffer): boolean
  /**
   * Batch push raw buffers (fastest batch path).
   *
   * Each buffer is one event. Returns count of successfully ingested.
   */
  pushBatch(events: Array<Buffer>): number
  /**
   * Ingest a raw JSON string synchronously (fastest path).
   *
   * This is the recommended method for high-throughput ingestion.
   * No async overhead - directly calls into Rust core.
   */
  ingestRawSync(json: string): IngestResult
  /**
   * Ingest multiple raw JSON strings in a batch synchronously.
   *
   * Most efficient method for bulk ingestion - single FFI boundary crossing.
   */
  ingestRawBatchSync(events: Array<string>): number
  /**
   * Fire-and-forget ingestion - returns immediately, no result.
   *
   * Fastest possible path when you don't need confirmation.
   */
  ingestFire(json: string): boolean
  /** Fire-and-forget batch ingestion - returns count only. */
  ingestBatchFire(events: Array<string>): number
  /**
   * Ingest a raw JSON string (async version).
   *
   * For maximum performance, use `ingestRawSync` instead.
   */
  ingestRaw(json: string): Promise<IngestResult>
  /**
   * Ingest a JavaScript object (convenience method).
   *
   * The object is serialized to JSON before ingestion.
   * For maximum performance, use `ingestRawSync` with pre-serialized JSON.
   */
  ingest(event: string): Promise<IngestResult>
  /**
   * Ingest multiple raw JSON strings in a batch (async version).
   *
   * For maximum performance, use `ingestRawBatchSync` instead.
   */
  ingestRawBatch(events: Array<string>): Promise<number>
  /** Poll events from the bus. */
  poll(options: PollOptions): Promise<PollResponse>
  /** Get the number of active shards. */
  numShards(): number
  /** Get ingestion statistics. */
  stats(): Stats
  /**
   * Flush all pending batches to the backend.
   *
   * Call this after ingesting events to ensure they are persisted
   * before polling.
   */
  flush(): Promise<void>
  /** Gracefully shutdown the event bus. */
  shutdown(): Promise<void>
}

/** Redis adapter configuration. */
export interface RedisOptions {
  /** Redis connection URL (e.g., "redis://localhost:6379") */
  url: string
  /** Stream key prefix (default: "net") */
  prefix?: string
  /** Maximum commands per pipeline (default: 1000) */
  pipelineSize?: number
  /** Connection pool size (default: num_shards) */
  poolSize?: number
  /** Connection timeout in milliseconds (default: 5000) */
  connectTimeoutMs?: number
  /** Command timeout in milliseconds (default: 1000) */
  commandTimeoutMs?: number
  /** Maximum stream length, unlimited if not set */
  maxStreamLen?: number
}

/** NATS JetStream adapter configuration. */
export interface JetStreamOptions {
  /** NATS server URL (e.g., "nats://localhost:4222") */
  url: string
  /** Stream name prefix (default: "net") */
  prefix?: string
  /** Connection timeout in milliseconds (default: 5000) */
  connectTimeoutMs?: number
  /** Request timeout in milliseconds (default: 5000) */
  requestTimeoutMs?: number
  /** Maximum messages per stream, unlimited if not set */
  maxMessages?: number
  /** Maximum bytes per stream, unlimited if not set */
  maxBytes?: number
  /** Maximum age for messages in milliseconds, unlimited if not set */
  maxAgeMs?: number
  /** Number of stream replicas (default: 1) */
  replicas?: number
}

/** Configuration options for creating an EventBus. */
export interface EventBusOptions {
  /** Number of shards (defaults to CPU core count) */
  numShards?: number
  /** Ring buffer capacity per shard (must be power of 2) */
  ringBufferCapacity?: number
  /** Backpressure mode: "drop_newest", "drop_oldest", "fail_producer" */
  backpressureMode?: string
  /** Redis adapter configuration */
  redis?: RedisOptions
  /** NATS JetStream adapter configuration */
  jetstream?: JetStreamOptions
}

/**
 * Pre-computed hash for events that will be reused.
 * Store on JS side and pass back to avoid recomputing xxhash.
 */
export interface HashedEvent {
  data: Buffer
  hash: bigint
}

/** Ingestion result. */
export interface IngestResult {
  /** Shard the event was assigned to */
  shardId: number
  /** Insertion timestamp */
  timestamp: number
}

/** Options for polling events. */
export interface PollOptions {
  /** Maximum number of events to return */
  limit: number
  /** Optional cursor to resume from */
  cursor?: string
  /** Optional JSON filter expression */
  filter?: string
  /** Event ordering: "none" (default, fastest) or "insertion_ts" (cross-shard ordering) */
  ordering?: string
}

/** Poll response containing events and cursor. */
export interface PollResponse {
  /** List of events */
  events: Array<StoredEvent>
  /** Cursor for pagination (pass to next poll) */
  nextId?: string
  /** Whether there are more events available */
  hasMore: boolean
}

/** Ingestion statistics. */
export interface Stats {
  /** Total events ingested */
  eventsIngested: number
  /** Events dropped due to backpressure */
  eventsDropped: number
}

/** A stored event returned from polling. */
export interface StoredEvent {
  /** Backend-specific event ID */
  id: string
  /** Raw JSON payload as string */
  raw: string
  /** Insertion timestamp (nanoseconds) */
  insertionTs: number
  /** Shard ID */
  shardId: number
}
