/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Typed memories adapter handle. */
export declare class MemoriesAdapter {
  /**
   * Open the memories adapter against a Redex manager. See
   * [`TasksAdapter::open`] for `persistent` semantics.
   */
  static open(redex: Redex, originHash: number, persistent?: boolean | undefined | null): Promise<MemoriesAdapter>
  /** Store a new memory. */
  store(id: bigint, content: string, tags: Array<string>, source: string, nowNs: bigint): bigint
  /**
   * Replace the tag set on an existing memory. No-op at fold time
   * if `id` is unknown.
   */
  retag(id: bigint, tags: Array<string>, nowNs: bigint): bigint
  /** Pin a memory. */
  pin(id: bigint, nowNs: bigint): bigint
  /** Unpin a memory. */
  unpin(id: bigint, nowNs: bigint): bigint
  /** Delete a memory. */
  delete(id: bigint): bigint
  /** Block until every event up through `seq` has been folded. */
  waitForSeq(seq: bigint): Promise<void>
  /** Close the adapter. Idempotent. */
  close(): void
  /** True if the fold task is currently running. */
  isRunning(): boolean
  /** Snapshot query. See [`MemoryFilter`] for available predicates. */
  listMemories(filter?: MemoryFilter | undefined | null): Array<Memory>
  /** Total memory count in current state (ignores any filter). */
  count(): number
  /**
   * Open a reactive watcher over the filter. See
   * [`TasksAdapter::watch_tasks`] for emission semantics.
   */
  watchMemories(filter?: MemoryFilter | undefined | null): Promise<MemoryWatchIter>
}

/** Async iterator over a live memory filter. */
export declare class MemoryWatchIter {
  /**
   * Wait for the next filter result. Returns `null` when the
   * iterator has been closed or the underlying stream has ended.
   */
  next(): Promise<Array<Memory> | null>
  /** Terminate the iterator early. Idempotent. */
  close(): void
}

/**
 * High-performance event bus for Node.js.
 *
 * Example usage:
 * ```typescript
 * import { Net } from '@ai2070/net';
 *
 * const bus = await Net.create({ numShards: 4 });
 *
 * // Fast sync ingestion (no async overhead)
 * bus.ingestRawSync('{"token": "hello", "index": 0}');
 *
 * // Or batch for maximum throughput
 * bus.ingestRawBatchSync(['{"a":1}', '{"a":2}']);
 *
 * // Poll events (async)
 * const response = await bus.poll({ limit: 100 });
 *
 * await bus.shutdown();
 * ```
 */
export declare class Net {
  /** Create a new Net event bus. */
  static create(options?: EventBusOptions | undefined | null): Promise<Net>
  /**
   * Pre-compute hash for an event buffer.
   *
   * Use this for events that will be ingested multiple times (e.g., templates).
   * The returned HashedEvent can be passed to pushHashed() to skip hash computation.
   */
  prehash(data: Buffer): HashedEvent
  /**
   * Ingest with a pre-computed hash (fastest single-event path).
   *
   * Pass the buffer and its pre-computed xxhash (as BigInt) to skip hash
   * computation. BigInt preserves full 64-bit precision.
   */
  pushWithHash(data: Buffer, hash: bigint): boolean
  /**
   * Ingest raw bytes (fastest single-event path).
   *
   * Accepts a Buffer directly from JS - no string conversion overhead.
   * Returns true on success, false on failure.
   */
  push(data: Buffer): boolean
  /**
   * Batch push raw buffers (fastest batch path).
   *
   * Each buffer is one event. Returns count of successfully ingested.
   */
  pushBatch(events: Array<Buffer>): number
  /**
   * Ingest a raw JSON string synchronously (fastest path).
   *
   * This is the recommended method for high-throughput ingestion.
   * No async overhead - directly calls into Rust core.
   */
  ingestRawSync(json: string): IngestResult
  /**
   * Ingest multiple raw JSON strings in a batch synchronously.
   *
   * Most efficient method for bulk ingestion - single FFI boundary crossing.
   */
  ingestRawBatchSync(events: Array<string>): number
  /**
   * Fire-and-forget ingestion - returns immediately, no result.
   *
   * Fastest possible path when you don't need confirmation.
   */
  ingestFire(json: string): boolean
  /** Fire-and-forget batch ingestion - returns count only. */
  ingestBatchFire(events: Array<string>): number
  /**
   * Ingest a raw JSON string (async version).
   *
   * For maximum performance, use `ingestRawSync` instead.
   */
  ingestRaw(json: string): Promise<IngestResult>
  /**
   * Ingest a JavaScript object (convenience method).
   *
   * The object is serialized to JSON before ingestion.
   * For maximum performance, use `ingestRawSync` with pre-serialized JSON.
   */
  ingest(event: string): Promise<IngestResult>
  /**
   * Ingest multiple raw JSON strings in a batch (async version).
   *
   * For maximum performance, use `ingestRawBatchSync` instead.
   */
  ingestRawBatch(events: Array<string>): Promise<number>
  /** Poll events from the bus. */
  poll(options: PollOptions): Promise<PollResponse>
  /** Get the number of active shards. */
  numShards(): number
  /** Get ingestion statistics. */
  stats(): Stats
  /**
   * Flush all pending batches to the backend.
   *
   * Call this after ingesting events to ensure they are persisted
   * before polling.
   */
  flush(): Promise<void>
  /**
   * Gracefully shutdown the event bus.
   *
   * Returns an error if there are outstanding references to the bus
   * (e.g., from concurrent async operations).
   */
  shutdown(): Promise<void>
}

/**
 * Local RedEX manager. Holds the set of open files on this node.
 *
 * Cheap to share — methods take `&self`.
 */
export declare class Redex {
  /**
   * Open a new Redex manager.
   *
   * `persistentDir`: if provided, files opened through adapters
   * with `persistent: true` write to `<persistentDir>/<channel_path>/{idx,dat}`
   * and replay from those files on reopen. Heap-only when omitted.
   */
  constructor(persistentDir?: string | undefined | null)
}

/** Typed tasks adapter handle. */
export declare class TasksAdapter {
  /**
   * Open the tasks adapter against a Redex manager.
   *
   * `persistent` — when `true`, the file writes to disk under the
   * Redex's configured persistent directory and replays from disk
   * on reopen. Requires the Redex to have been constructed with
   * `persistentDir`; otherwise `open()` errors.
   *
   * Declared `async` so napi-rs runs it with its tokio runtime
   * active — the underlying `CortexAdapter::open` spawns the
   * fold task via `tokio::spawn` and needs a live reactor.
   */
  static open(redex: Redex, originHash: number, persistent?: boolean | undefined | null): Promise<TasksAdapter>
  /** Create a new task. Returns the RedEX sequence of the append. */
  create(id: bigint, title: string, nowNs: bigint): bigint
  /** Rename an existing task. No-op at fold time if `id` is unknown. */
  rename(id: bigint, newTitle: string, nowNs: bigint): bigint
  /** Mark a task completed. No-op at fold time if `id` is unknown. */
  complete(id: bigint, nowNs: bigint): bigint
  /** Delete a task. */
  delete(id: bigint): bigint
  /**
   * Block until every event up through `seq` has been folded into
   * state. Use as a read-after-write barrier.
   */
  waitForSeq(seq: bigint): Promise<void>
  /** Close the adapter. Idempotent. */
  close(): void
  /** True if the fold task is currently running. */
  isRunning(): boolean
  /**
   * Snapshot query over current state. Clones out matching tasks
   * as a Vec. Pass `null` / `undefined` for no filter (returns all).
   */
  listTasks(filter?: TaskFilter | undefined | null): Array<Task>
  /** Total task count in current state (ignores any filter). */
  count(): number
  /**
   * Open a reactive watcher over the filter. Returns an iterator
   * whose `.next()` yields the current filter result on first
   * call, then yields again whenever a fold tick produces a
   * different filter result (deduplicated).
   *
   * Declared `async` so the underlying watcher's `tokio::spawn`
   * fold-forwarding task runs inside napi's tokio runtime.
   */
  watchTasks(filter?: TaskFilter | undefined | null): Promise<TaskWatchIter>
}

/**
 * Async iterator over a live task filter.
 *
 * Rust returns `null` from [`Self::next`] when the underlying
 * watcher ends; JS should treat that as `done: true`. Paired with
 * the JS helper in the test suite below, this cleanly wraps into a
 * `for await (const tasks of ...)` loop.
 */
export declare class TaskWatchIter {
  /**
   * Wait for the next filter result. Returns `null` when the
   * iterator has been closed or the underlying stream has ended.
   */
  next(): Promise<Array<Task> | null>
  /**
   * Terminate the iterator early. Any pending `next()` call
   * resolves to `null`. Subsequent `next()` calls also return
   * `null`. Idempotent.
   */
  close(): void
}

/** Configuration options for creating an EventBus. */
export interface EventBusOptions {
  /** Number of shards (defaults to CPU core count) */
  numShards?: number
  /** Ring buffer capacity per shard (must be power of 2) */
  ringBufferCapacity?: number
  /** Backpressure mode: "drop_newest", "drop_oldest", "fail_producer" */
  backpressureMode?: string
  /** Redis adapter configuration (if not set, uses in-memory noop adapter) */
  redis?: RedisOptions
  /** NATS JetStream adapter configuration (alternative to Redis) */
  jetstream?: JetStreamOptions
  /** Net adapter configuration for encrypted UDP transport */
  net?: NetOptions
}

/**
 * Pre-computed hash for events that will be reused.
 * Store on JS side and pass back to avoid recomputing xxhash.
 *
 * Hash is exposed as BigInt to preserve full 64-bit xxh3 precision.
 */
export interface HashedEvent {
  data: Buffer
  hash: bigint
}

/** Ingestion result. */
export interface IngestResult {
  /** Shard the event was assigned to */
  shardId: number
  /** Insertion timestamp */
  timestamp: number
}

/** NATS JetStream adapter configuration. */
export interface JetStreamOptions {
  /** NATS server URL (e.g., "nats://localhost:4222") */
  url: string
  /** Stream name prefix (default: "net") */
  prefix?: string
  /** Connection timeout in milliseconds (default: 5000) */
  connectTimeoutMs?: number
  /** Request timeout in milliseconds (default: 5000) */
  requestTimeoutMs?: number
  /** Maximum messages per stream, unlimited if not set */
  maxMessages?: number
  /** Maximum bytes per stream, unlimited if not set */
  maxBytes?: number
  /** Maximum age for messages in milliseconds, unlimited if not set */
  maxAgeMs?: number
  /** Number of stream replicas (default: 1) */
  replicas?: number
}

/** Ordering for memory queries. */
export declare const enum MemoriesOrderBy {
  IdAsc = 'IdAsc',
  IdDesc = 'IdDesc',
  CreatedAsc = 'CreatedAsc',
  CreatedDesc = 'CreatedDesc',
  UpdatedAsc = 'UpdatedAsc',
  UpdatedDesc = 'UpdatedDesc'
}

/** A materialized memory record. */
export interface Memory {
  id: bigint
  content: string
  tags: Array<string>
  source: string
  createdNs: bigint
  updatedNs: bigint
  pinned: boolean
}

/**
 * Filter for [`MemoriesAdapter::list_memories`] and
 * [`MemoriesAdapter::watch_memories`]. Tag predicates:
 *
 * - `tag` — must include this exact tag.
 * - `any_tag` — must include at least one tag from the array.
 * - `all_tags` — must include every tag in the array.
 */
export interface MemoryFilter {
  source?: string
  contentContains?: string
  tag?: string
  anyTag?: Array<string>
  allTags?: Array<string>
  pinned?: boolean
  createdAfterNs?: bigint
  createdBeforeNs?: bigint
  updatedAfterNs?: bigint
  updatedBeforeNs?: bigint
  orderBy?: MemoriesOrderBy
  limit?: number
}

/** Net keypair for encrypted UDP transport. */
export interface NetKeypair {
  /** Hex-encoded 32-byte public key */
  publicKey: string
  /** Hex-encoded 32-byte secret key */
  secretKey: string
}

/** Net adapter configuration for encrypted UDP transport. */
export interface NetOptions {
  /** Local bind address (e.g., "127.0.0.1:9000") */
  bindAddr: string
  /** Remote peer address (e.g., "127.0.0.1:9001") */
  peerAddr: string
  /** Hex-encoded 32-byte pre-shared key */
  psk: string
  /** Connection role: "initiator" or "responder" */
  role: string
  /** Hex-encoded peer's static public key (required for initiator) */
  peerPublicKey?: string
  /** Hex-encoded secret key (required for responder) */
  secretKey?: string
  /** Hex-encoded public key (required for responder) */
  publicKey?: string
  /** Reliability mode: "none" (default), "light", or "full" */
  reliability?: string
  /** Heartbeat interval in milliseconds (default: 5000) */
  heartbeatIntervalMs?: number
  /** Session timeout in milliseconds (default: 30000) */
  sessionTimeoutMs?: number
  /** Enable batched I/O for Linux (default: false) */
  batchedIo?: boolean
  /** Packet pool size (default: 64) */
  packetPoolSize?: number
}

/** Options for polling events. */
export interface PollOptions {
  /** Maximum number of events to return */
  limit: number
  /** Optional cursor to resume from */
  cursor?: string
  /** Optional JSON filter expression */
  filter?: string
  /** Event ordering: "none" (default, fastest) or "insertion_ts" (cross-shard ordering) */
  ordering?: string
}

/** Poll response containing events and cursor. */
export interface PollResponse {
  /** List of events */
  events: Array<StoredEvent>
  /** Cursor for pagination (pass to next poll) */
  nextId?: string
  /** Whether there are more events available */
  hasMore: boolean
}

/** Redis adapter configuration. */
export interface RedisOptions {
  /** Redis connection URL (e.g., "redis://localhost:6379") */
  url: string
  /** Stream key prefix (default: "net") */
  prefix?: string
  /** Maximum commands per pipeline (default: 1000) */
  pipelineSize?: number
  /** Connection pool size (default: num_shards) */
  poolSize?: number
  /** Connection timeout in milliseconds (default: 5000) */
  connectTimeoutMs?: number
  /** Command timeout in milliseconds (default: 1000) */
  commandTimeoutMs?: number
  /** Maximum stream length, unlimited if not set */
  maxStreamLen?: number
}

/** Ingestion statistics. */
export interface Stats {
  /** Total events ingested */
  eventsIngested: number
  /** Events dropped due to backpressure */
  eventsDropped: number
}

/** A stored event returned from polling. */
export interface StoredEvent {
  /** Backend-specific event ID */
  id: string
  /**
   * Raw payload as UTF-8. When the payload is not valid UTF-8
   * (binary payloads), this is the empty string and the original
   * bytes are in `raw_bytes` instead.
   */
  raw: string
  /**
   * Raw payload bytes. Always populated — consumers that need binary
   * fidelity should prefer this over `raw`. For UTF-8 payloads the
   * two fields carry the same content in different representations.
   */
  rawBytes: Buffer
  /** Insertion timestamp (nanoseconds) */
  insertionTs: number
  /** Shard ID */
  shardId: number
}

/** A materialized task record. */
export interface Task {
  id: bigint
  title: string
  status: TaskStatus
  createdNs: bigint
  updatedNs: bigint
}

/**
 * Filter for [`TasksAdapter::list_tasks`] and
 * [`TasksAdapter::watch_tasks`].
 */
export interface TaskFilter {
  status?: TaskStatus
  titleContains?: string
  createdAfterNs?: bigint
  createdBeforeNs?: bigint
  updatedAfterNs?: bigint
  updatedBeforeNs?: bigint
  orderBy?: TasksOrderBy
  limit?: number
}

/** Ordering for task queries. */
export declare const enum TasksOrderBy {
  IdAsc = 'IdAsc',
  IdDesc = 'IdDesc',
  CreatedAsc = 'CreatedAsc',
  CreatedDesc = 'CreatedDesc',
  UpdatedAsc = 'UpdatedAsc',
  UpdatedDesc = 'UpdatedDesc'
}

/** Task lifecycle status. */
export declare const enum TaskStatus {
  Pending = 'Pending',
  Completed = 'Completed'
}
