/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Typed memories adapter handle. */
export declare class MemoriesAdapter {
  /**
   * Open the memories adapter against a Redex manager. See
   * [`TasksAdapter::open`] for `persistent` semantics.
   */
  static open(redex: Redex, originHash: number, persistent?: boolean | undefined | null): Promise<MemoriesAdapter>
  /** Open from a snapshot captured via [`Self::snapshot`]. */
  static openFromSnapshot(redex: Redex, originHash: number, stateBytes: Buffer, lastSeq?: bigint | undefined | null, persistent?: boolean | undefined | null): Promise<MemoriesAdapter>
  /**
   * Capture a state snapshot for restore via
   * [`Self::open_from_snapshot`].
   */
  snapshot(): CortexSnapshot
  /** Store a new memory. */
  store(id: bigint, content: string, tags: Array<string>, source: string, nowNs: bigint): bigint
  /**
   * Replace the tag set on an existing memory. No-op at fold time
   * if `id` is unknown.
   */
  retag(id: bigint, tags: Array<string>, nowNs: bigint): bigint
  /** Pin a memory. */
  pin(id: bigint, nowNs: bigint): bigint
  /** Unpin a memory. */
  unpin(id: bigint, nowNs: bigint): bigint
  /** Delete a memory. */
  delete(id: bigint): bigint
  /** Block until every event up through `seq` has been folded. */
  waitForSeq(seq: bigint): Promise<void>
  /** Close the adapter. Idempotent. */
  close(): void
  /** True if the fold task is currently running. */
  isRunning(): boolean
  /** Snapshot query. See [`MemoryFilter`] for available predicates. */
  listMemories(filter?: MemoryFilter | undefined | null): Array<Memory>
  /** Total memory count in current state (ignores any filter). */
  count(): number
  /**
   * Open a reactive watcher over the filter. See
   * [`TasksAdapter::watch_tasks`] for emission semantics.
   */
  watchMemories(filter?: MemoryFilter | undefined | null): Promise<MemoryWatchIter>
  /**
   * Atomic "paint + react" primitive. Mirrors
   * [`TasksAdapter::snapshot_and_watch_tasks`] for memories.
   */
  snapshotAndWatchMemories(filter?: MemoryFilter | undefined | null): Promise<MemoriesSnapshotAndWatch>
}

/** Result of [`MemoriesAdapter::snapshot_and_watch_memories`]. */
export declare class MemoriesSnapshotAndWatch {
  /** Initial filter result captured atomically with the watcher. */
  get snapshot(): Array<Memory>
  /** Wait for the next delta. `null` when closed / ended. */
  next(): Promise<Array<Memory> | null>
  /** Terminate the iterator early. Idempotent. */
  close(): void
}

/** Async iterator over a live memory filter. */
export declare class MemoryWatchIter {
  /**
   * Wait for the next filter result. Returns `null` when the
   * iterator has been closed or the underlying stream has ended.
   */
  next(): Promise<Array<Memory> | null>
  /** Terminate the iterator early. Idempotent. */
  close(): void
}

/**
 * High-performance event bus for Node.js.
 *
 * Example usage:
 * ```typescript
 * import { Net } from '@ai2070/net';
 *
 * const bus = await Net.create({ numShards: 4 });
 *
 * // Fast sync ingestion (no async overhead)
 * bus.ingestRawSync('{"token": "hello", "index": 0}');
 *
 * // Or batch for maximum throughput
 * bus.ingestRawBatchSync(['{"a":1}', '{"a":2}']);
 *
 * // Poll events (async)
 * const response = await bus.poll({ limit: 100 });
 *
 * await bus.shutdown();
 * ```
 */
export declare class Net {
  /** Create a new Net event bus. */
  static create(options?: EventBusOptions | undefined | null): Promise<Net>
  /**
   * Pre-compute hash for an event buffer.
   *
   * Use this for events that will be ingested multiple times (e.g., templates).
   * The returned HashedEvent can be passed to pushHashed() to skip hash computation.
   */
  prehash(data: Buffer): HashedEvent
  /**
   * Ingest with a pre-computed hash (fastest single-event path).
   *
   * Pass the buffer and its pre-computed xxhash (as BigInt) to skip hash
   * computation. BigInt preserves full 64-bit precision.
   */
  pushWithHash(data: Buffer, hash: bigint): boolean
  /**
   * Ingest raw bytes (fastest single-event path).
   *
   * Accepts a Buffer directly from JS - no string conversion overhead.
   * Returns true on success, false on failure.
   */
  push(data: Buffer): boolean
  /**
   * Batch push raw buffers (fastest batch path).
   *
   * Each buffer is one event. Returns count of successfully ingested.
   */
  pushBatch(events: Array<Buffer>): number
  /**
   * Ingest a raw JSON string synchronously (fastest path).
   *
   * This is the recommended method for high-throughput ingestion.
   * No async overhead - directly calls into Rust core.
   */
  ingestRawSync(json: string): IngestResult
  /**
   * Ingest multiple raw JSON strings in a batch synchronously.
   *
   * Most efficient method for bulk ingestion - single FFI boundary crossing.
   */
  ingestRawBatchSync(events: Array<string>): number
  /**
   * Fire-and-forget ingestion - returns immediately, no result.
   *
   * Fastest possible path when you don't need confirmation.
   */
  ingestFire(json: string): boolean
  /** Fire-and-forget batch ingestion - returns count only. */
  ingestBatchFire(events: Array<string>): number
  /**
   * Ingest a raw JSON string (async version).
   *
   * For maximum performance, use `ingestRawSync` instead.
   */
  ingestRaw(json: string): Promise<IngestResult>
  /**
   * Ingest a JavaScript object (convenience method).
   *
   * The object is serialized to JSON before ingestion.
   * For maximum performance, use `ingestRawSync` with pre-serialized JSON.
   */
  ingest(event: string): Promise<IngestResult>
  /**
   * Ingest multiple raw JSON strings in a batch (async version).
   *
   * For maximum performance, use `ingestRawBatchSync` instead.
   */
  ingestRawBatch(events: Array<string>): Promise<number>
  /** Poll events from the bus. */
  poll(options: PollOptions): Promise<PollResponse>
  /** Get the number of active shards. */
  numShards(): number
  /** Get ingestion statistics. */
  stats(): Stats
  /**
   * Flush all pending batches to the backend.
   *
   * Call this after ingesting events to ensure they are persisted
   * before polling.
   */
  flush(): Promise<void>
  /**
   * Gracefully shutdown the event bus.
   *
   * Returns an error if there are outstanding references to the bus
   * (e.g., from concurrent async operations).
   */
  shutdown(): Promise<void>
}

/**
 * Unified NetDB handle. Bundles `TasksAdapter` + `MemoriesAdapter`
 * under one object; access them via `.tasks` / `.memories` getters.
 *
 * NetDB is the recommended entry point for callers that want a
 * database-like surface. For raw event / stream access, drop down
 * to the individual adapters.
 */
export declare class NetDb {
  /**
   * Open a NetDB with the requested models. Each enabled model
   * spawns its own CortEX fold task.
   */
  static open(config: NetDbOpenConfig): Promise<NetDb>
  /**
   * Open a NetDB and restore each enabled model's state from the
   * bundle. Models whose bundle entry is `None` are opened from
   * scratch (equivalent to [`Self::open`] for that model).
   */
  static openFromSnapshot(config: NetDbOpenConfig, bundle: NetDbBundle): Promise<NetDb>
  /** The tasks adapter (or `null` if tasks weren't enabled). */
  get tasks(): TasksAdapter | null
  /** The memories adapter (or `null` if memories weren't enabled). */
  get memories(): MemoriesAdapter | null
  /**
   * Snapshot every enabled model into one bundle. Persist the
   * `stateBytes` blob; restore via [`Self::open_from_snapshot`].
   */
  snapshot(): NetDbBundle
  /** Close every enabled adapter. Idempotent. */
  close(): void
}

/**
 * A multi-peer mesh node for Node.js.
 *
 * Manages encrypted connections to multiple peers over a single
 * UDP socket with automatic failure detection and rerouting.
 *
 * ```typescript
 * import { NetMesh } from '@ai2070/net';
 *
 * const node = await NetMesh.create({
 *   bindAddr: '127.0.0.1:9000',
 *   psk: '0'.repeat(64), // 32-byte hex
 * });
 *
 * console.log('public key:', node.publicKey());
 *
 * await node.connect('127.0.0.1:9001', peerPubkey, 0x2222);
 * node.start();
 *
 * node.pushTo('127.0.0.1:9001', Buffer.from('{"token":"hi"}'));
 *
 * const events = await node.poll(100);
 *
 * await node.shutdown();
 * ```
 */
export declare class NetMesh {
  /** Create a new mesh node. */
  static create(options: MeshOptions): Promise<NetMesh>
  /** Get this node's Noise public key (hex-encoded). */
  publicKey(): string
  /**
   * Get this node's ID.
   *
   * Returned as `i64` to fit JavaScript's `number` semantics. Fails
   * rather than wraps when the `u64` node_id exceeds `i64::MAX`,
   * which would otherwise silently flip sign on the JS side.
   */
  nodeId(): number
  /** Connect to a peer (initiator side). */
  connect(peerAddr: string, peerPublicKey: string, peerNodeId: number): Promise<void>
  /** Accept an incoming connection (responder side). */
  accept(peerNodeId: number): Promise<string>
  /** Start the receive loop, heartbeats, and router. */
  start(): void
  /** Send raw bytes to a direct peer. */
  pushTo(peerAddr: string, data: Buffer): Promise<boolean>
  /** Poll for received events. */
  poll(limit: number): Promise<Array<StoredEvent>>
  /** Add a route to a destination node. */
  addRoute(destNodeId: number, nextHopAddr: string): void
  /** Number of connected peers. */
  peerCount(): number
  /** Number of nodes discovered via pingwave. */
  discoveredNodes(): number
  /**
   * Open (or look up) a stream to a connected peer. Repeated
   * calls for the same `(peer, streamId)` return handles to the
   * same underlying state (first-open wins; differing configs
   * are logged and ignored).
   */
  openStream(peerNodeId: number, opts: StreamOptions): NetStream
  /** Close a stream. Idempotent. */
  closeStream(peerNodeId: number, streamId: number): void
  /**
   * Send a batch of events on an explicit stream.
   *
   * **Error contract for SDK wrappers:** message prefixes are
   * stable. `"stream would block"` = `BackpressureError`;
   * `"stream not connected"` = `NotConnectedError`; anything
   * else is a real transport failure. See `sdk-ts` for the
   * class-based re-throw layer.
   */
  sendOnStream(stream: NetStream, events: Array<Buffer>): Promise<void>
  /**
   * Send events, retrying on `Backpressure` with 5 ms → 200 ms
   * exponential backoff up to `maxRetries` times. Transport
   * errors are returned immediately (not retried).
   */
  sendWithRetry(stream: NetStream, events: Array<Buffer>, maxRetries: number): Promise<void>
  /**
   * Block the calling JS task until the send succeeds or a
   * transport error occurs. Retries `Backpressure` with 5 ms →
   * 200 ms exponential backoff up to 4096 times (~13 min worst
   * case) — effectively "block until the network lets up" for
   * practical workloads, but with a hard upper bound so runaway
   * pressure can't hang a caller forever. Use `sendWithRetry`
   * directly if you need a tighter bound.
   */
  sendBlocking(stream: NetStream, events: Array<Buffer>): Promise<void>
  /**
   * Snapshot of per-stream stats. Returns `null` if the peer or
   * stream isn't registered.
   */
  streamStats(peerNodeId: number, streamId: number): NetStreamStats | null
  /** Shutdown the mesh node. */
  shutdown(): Promise<void>
}

/**
 * Handle to an open stream. Opaque to JS callers; pass back to
 * `sendOnStream` / `sendWithRetry` / `sendBlocking` / `closeStream`.
 */
export declare class NetStream {
  /** The peer this stream terminates at. */
  get peerNodeId(): number
  /** The caller-chosen stream id. */
  get streamId(): number
}

/**
 * Local RedEX manager. Holds the set of open files on this node.
 *
 * Cheap to share — methods take `&self`.
 */
export declare class Redex {
  /**
   * Open a new Redex manager.
   *
   * `persistentDir`: if provided, files opened through adapters
   * with `persistent: true` write to `<persistentDir>/<channel_path>/{idx,dat}`
   * and replay from those files on reopen. Heap-only when omitted.
   */
  constructor(persistentDir?: string | undefined | null)
}

/** Typed tasks adapter handle. */
export declare class TasksAdapter {
  /**
   * Open the tasks adapter against a Redex manager.
   *
   * `persistent` — when `true`, the file writes to disk under the
   * Redex's configured persistent directory and replays from disk
   * on reopen. Requires the Redex to have been constructed with
   * `persistentDir`; otherwise `open()` errors.
   *
   * Declared `async` so napi-rs runs it with its tokio runtime
   * active — the underlying `CortexAdapter::open` spawns the
   * fold task via `tokio::spawn` and needs a live reactor.
   */
  static open(redex: Redex, originHash: number, persistent?: boolean | undefined | null): Promise<TasksAdapter>
  /**
   * Open from a snapshot captured via [`Self::snapshot`]. Skips
   * replay of events `[0, lastSeq]` on the underlying file.
   */
  static openFromSnapshot(redex: Redex, originHash: number, stateBytes: Buffer, lastSeq?: bigint | undefined | null, persistent?: boolean | undefined | null): Promise<TasksAdapter>
  /**
   * Capture a state snapshot. Persist both fields together; restore
   * via [`Self::open_from_snapshot`].
   */
  snapshot(): CortexSnapshot
  /** Create a new task. Returns the RedEX sequence of the append. */
  create(id: bigint, title: string, nowNs: bigint): bigint
  /** Rename an existing task. No-op at fold time if `id` is unknown. */
  rename(id: bigint, newTitle: string, nowNs: bigint): bigint
  /** Mark a task completed. No-op at fold time if `id` is unknown. */
  complete(id: bigint, nowNs: bigint): bigint
  /** Delete a task. */
  delete(id: bigint): bigint
  /**
   * Block until every event up through `seq` has been folded into
   * state. Use as a read-after-write barrier.
   */
  waitForSeq(seq: bigint): Promise<void>
  /** Close the adapter. Idempotent. */
  close(): void
  /** True if the fold task is currently running. */
  isRunning(): boolean
  /**
   * Snapshot query over current state. Clones out matching tasks
   * as a Vec. Pass `null` / `undefined` for no filter (returns all).
   */
  listTasks(filter?: TaskFilter | undefined | null): Array<Task>
  /** Total task count in current state (ignores any filter). */
  count(): number
  /**
   * Open a reactive watcher over the filter. Returns an iterator
   * whose `.next()` yields the current filter result on first
   * call, then yields again whenever a fold tick produces a
   * different filter result (deduplicated).
   *
   * Declared `async` so the underlying watcher's `tokio::spawn`
   * fold-forwarding task runs inside napi's tokio runtime.
   */
  watchTasks(filter?: TaskFilter | undefined | null): Promise<TaskWatchIter>
  /**
   * Atomic "paint what's here now, then react to changes" primitive.
   * Computes the current filter result AND hands back an iterator
   * over subsequent deltas in one call so the caller can't race a
   * mutation that lands between a separate `listTasks` and
   * `watchTasks`. The iterator drops only leading emissions equal
   * to the returned snapshot; if a change lands during construction,
   * the watcher's first emission is forwarded through instead of
   * being silently dropped.
   *
   * Declared `async` for the same tokio-runtime reason as
   * [`Self::watch_tasks`].
   */
  snapshotAndWatchTasks(filter?: TaskFilter | undefined | null): Promise<TasksSnapshotAndWatch>
}

/**
 * Result of [`TasksAdapter::snapshot_and_watch_tasks`]. The snapshot
 * reflects the filter result at the moment of the call; `next()` /
 * `close()` drive the delta iterator for subsequent changes.
 */
export declare class TasksSnapshotAndWatch {
  /**
   * The initial filter result, captured atomically with the
   * watcher. Clone-on-read; safe to call from JS without
   * invalidating the iterator.
   */
  get snapshot(): Array<Task>
  /**
   * Wait for the next delta. Returns `null` when the iterator has
   * been closed or the underlying stream has ended. Mirrors
   * [`TaskWatchIter::next`].
   */
  next(): Promise<Array<Task> | null>
  /** Terminate the iterator early. Idempotent. */
  close(): void
}

/**
 * Async iterator over a live task filter.
 *
 * Rust returns `null` from [`Self::next`] when the underlying
 * watcher ends; JS should treat that as `done: true`. Paired with
 * the JS helper in the test suite below, this cleanly wraps into a
 * `for await (const tasks of ...)` loop.
 */
export declare class TaskWatchIter {
  /**
   * Wait for the next filter result. Returns `null` when the
   * iterator has been closed or the underlying stream has ended.
   */
  next(): Promise<Array<Task> | null>
  /**
   * Terminate the iterator early. Any pending `next()` call
   * resolves to `null`. Subsequent `next()` calls also return
   * `null`. Idempotent.
   */
  close(): void
}

/**
 * A captured CortEX adapter state snapshot, suitable for
 * `openFromSnapshot`. Callers persist both fields together.
 */
export interface CortexSnapshot {
  /** bincode-serialized materialized state. */
  stateBytes: Buffer
  /**
   * Highest RedEX sequence folded into `state_bytes`. `null` if
   * no event had been folded at snapshot time.
   */
  lastSeq?: bigint
}

/** Configuration options for creating an EventBus. */
export interface EventBusOptions {
  /** Number of shards (defaults to CPU core count) */
  numShards?: number
  /** Ring buffer capacity per shard (must be power of 2) */
  ringBufferCapacity?: number
  /** Backpressure mode: "drop_newest", "drop_oldest", "fail_producer" */
  backpressureMode?: string
  /** Redis adapter configuration (if not set, uses in-memory noop adapter) */
  redis?: RedisOptions
  /** NATS JetStream adapter configuration (alternative to Redis) */
  jetstream?: JetStreamOptions
  /** Net adapter configuration for encrypted UDP transport */
  net?: NetOptions
}

/**
 * Generate a new Net keypair for encrypted UDP transport.
 *
 * Returns a keypair with hex-encoded public and secret keys.
 * Use this to generate keys for a responder, then share the public key
 * with the initiator.
 */
export declare function generateNetKeypair(): NetKeypair

/**
 * Pre-computed hash for events that will be reused.
 * Store on JS side and pass back to avoid recomputing xxhash.
 *
 * Hash is exposed as BigInt to preserve full 64-bit xxh3 precision.
 */
export interface HashedEvent {
  data: Buffer
  hash: bigint
}

/** Ingestion result. */
export interface IngestResult {
  /** Shard the event was assigned to */
  shardId: number
  /** Insertion timestamp */
  timestamp: number
}

/** NATS JetStream adapter configuration. */
export interface JetStreamOptions {
  /** NATS server URL (e.g., "nats://localhost:4222") */
  url: string
  /** Stream name prefix (default: "net") */
  prefix?: string
  /** Connection timeout in milliseconds (default: 5000) */
  connectTimeoutMs?: number
  /** Request timeout in milliseconds (default: 5000) */
  requestTimeoutMs?: number
  /** Maximum messages per stream, unlimited if not set */
  maxMessages?: number
  /** Maximum bytes per stream, unlimited if not set */
  maxBytes?: number
  /** Maximum age for messages in milliseconds, unlimited if not set */
  maxAgeMs?: number
  /** Number of stream replicas (default: 1) */
  replicas?: number
}

/** Ordering for memory queries. */
export declare const enum MemoriesOrderBy {
  IdAsc = 'IdAsc',
  IdDesc = 'IdDesc',
  CreatedAsc = 'CreatedAsc',
  CreatedDesc = 'CreatedDesc',
  UpdatedAsc = 'UpdatedAsc',
  UpdatedDesc = 'UpdatedDesc'
}

/** A materialized memory record. */
export interface Memory {
  id: bigint
  content: string
  tags: Array<string>
  source: string
  createdNs: bigint
  updatedNs: bigint
  pinned: boolean
}

/**
 * Filter for [`MemoriesAdapter::list_memories`] and
 * [`MemoriesAdapter::watch_memories`]. Tag predicates:
 *
 * - `tag` — must include this exact tag.
 * - `any_tag` — must include at least one tag from the array.
 * - `all_tags` — must include every tag in the array.
 */
export interface MemoryFilter {
  source?: string
  contentContains?: string
  tag?: string
  anyTag?: Array<string>
  allTags?: Array<string>
  pinned?: boolean
  createdAfterNs?: bigint
  createdBeforeNs?: bigint
  updatedAfterNs?: bigint
  updatedBeforeNs?: bigint
  orderBy?: MemoriesOrderBy
  limit?: number
}

/** Configuration for creating a MeshNode. */
export interface MeshOptions {
  /** Local bind address (e.g., "127.0.0.1:9000") */
  bindAddr: string
  /** Hex-encoded 32-byte pre-shared key */
  psk: string
  /** Heartbeat interval in milliseconds (default: 5000) */
  heartbeatIntervalMs?: number
  /** Session timeout in milliseconds (default: 30000) */
  sessionTimeoutMs?: number
  /** Number of inbound shards (default: 4) */
  numShards?: number
}

/**
 * Serialized NetDB snapshot bundle returned by [`NetDb::snapshot`]
 * and consumed by [`NetDb::open_from_snapshot`].
 */
export interface NetDbBundle {
  /** Bincode-encoded [`InnerNetDbSnapshot`] — opaque to callers. */
  stateBytes: Buffer
}

/** Options for [`NetDb::open`] / [`NetDb::open_from_snapshot`]. */
export interface NetDbOpenConfig {
  /**
   * Optional persistent base directory. When set, adapters opened
   * with `persistent: true` write to `<dir>/<channel_path>/{idx,dat}`.
   */
  persistentDir?: string
  /** Producer origin hash stamped on every `EventMeta`. */
  originHash: number
  /**
   * Open enabled adapters with `persistent: true`. Requires
   * `persistentDir`.
   */
  persistent?: boolean
  /** Include the tasks model. */
  withTasks?: boolean
  /** Include the memories model. */
  withMemories?: boolean
}

/** Net keypair for encrypted UDP transport. */
export interface NetKeypair {
  /** Hex-encoded 32-byte public key */
  publicKey: string
  /** Hex-encoded 32-byte secret key */
  secretKey: string
}

/** Net adapter configuration for encrypted UDP transport. */
export interface NetOptions {
  /** Local bind address (e.g., "127.0.0.1:9000") */
  bindAddr: string
  /** Remote peer address (e.g., "127.0.0.1:9001") */
  peerAddr: string
  /** Hex-encoded 32-byte pre-shared key */
  psk: string
  /** Connection role: "initiator" or "responder" */
  role: string
  /** Hex-encoded peer's static public key (required for initiator) */
  peerPublicKey?: string
  /** Hex-encoded secret key (required for responder) */
  secretKey?: string
  /** Hex-encoded public key (required for responder) */
  publicKey?: string
  /** Reliability mode: "none" (default), "light", or "full" */
  reliability?: string
  /** Heartbeat interval in milliseconds (default: 5000) */
  heartbeatIntervalMs?: number
  /** Session timeout in milliseconds (default: 30000) */
  sessionTimeoutMs?: number
  /** Enable batched I/O for Linux (default: false) */
  batchedIo?: boolean
  /** Packet pool size (default: 64) */
  packetPoolSize?: number
}

/**
 * Snapshot of per-stream stats.
 *
 * u64 fields are exposed as `BigInt` so values outside the JS
 * safe-integer range (notably `last_activity_ns`, which is
 * Unix-epoch nanoseconds and always well above `2^53`) don't
 * lose precision or trip the TS SDK's safe-integer guard. The
 * u32 fields are safe as regular numbers.
 */
export interface NetStreamStats {
  txSeq: bigint
  rxSeq: bigint
  inboundPending: bigint
  lastActivityNs: bigint
  active: boolean
  backpressureEvents: bigint
  txCreditRemaining: number
  txWindow: number
  creditGrantsReceived: bigint
  creditGrantsSent: bigint
}

/** Options for polling events. */
export interface PollOptions {
  /** Maximum number of events to return */
  limit: number
  /** Optional cursor to resume from */
  cursor?: string
  /** Optional JSON filter expression */
  filter?: string
  /** Event ordering: "none" (default, fastest) or "insertion_ts" (cross-shard ordering) */
  ordering?: string
}

/** Poll response containing events and cursor. */
export interface PollResponse {
  /** List of events */
  events: Array<StoredEvent>
  /** Cursor for pagination (pass to next poll) */
  nextId?: string
  /** Whether there are more events available */
  hasMore: boolean
}

/** Redis adapter configuration. */
export interface RedisOptions {
  /** Redis connection URL (e.g., "redis://localhost:6379") */
  url: string
  /** Stream key prefix (default: "net") */
  prefix?: string
  /** Maximum commands per pipeline (default: 1000) */
  pipelineSize?: number
  /** Connection pool size (default: num_shards) */
  poolSize?: number
  /** Connection timeout in milliseconds (default: 5000) */
  connectTimeoutMs?: number
  /** Command timeout in milliseconds (default: 1000) */
  commandTimeoutMs?: number
  /** Maximum stream length, unlimited if not set */
  maxStreamLen?: number
}

/** Ingestion statistics. */
export interface Stats {
  /** Total events ingested */
  eventsIngested: number
  /** Events dropped due to backpressure */
  eventsDropped: number
}

/** A stored event returned from polling. */
export interface StoredEvent {
  /** Backend-specific event ID */
  id: string
  /**
   * Raw payload as UTF-8. When the payload is not valid UTF-8
   * (binary payloads), this is the empty string and the original
   * bytes are in `raw_bytes` instead.
   */
  raw: string
  /**
   * Raw payload bytes. Always populated — consumers that need binary
   * fidelity should prefer this over `raw`. For UTF-8 payloads the
   * two fields carry the same content in different representations.
   */
  rawBytes: Buffer
  /** Insertion timestamp (nanoseconds) */
  insertionTs: number
  /** Shard ID */
  shardId: number
}

/**
 * Reliability mode for a stream. Wire value is a plain tag string:
 * `"fire_and_forget"` (default) or `"reliable"`. Anything else
 * errors at stream-open time.
 */
export interface StreamOptions {
  /**
   * Caller-chosen `u64` stream id. Stream IDs are opaque; no
   * range has transport-level meaning.
   */
  streamId: number
  /** `"fire_and_forget"` | `"reliable"`. Default: `"fire_and_forget"`. */
  reliability?: string
  /**
   * Initial send-credit window in bytes. Defaults to
   * `DEFAULT_STREAM_WINDOW_BYTES` (64 KB) when unset — v2
   * backpressure is ON out of the box. Pass `0` to restore the
   * v1 unbounded-queue behavior for a specific stream.
   */
  windowBytes?: number
  /** Fair-scheduler weight (1 = equal share). Default: 1. */
  fairnessWeight?: number
}

/** A materialized task record. */
export interface Task {
  id: bigint
  title: string
  status: TaskStatus
  createdNs: bigint
  updatedNs: bigint
}

/**
 * Filter for [`TasksAdapter::list_tasks`] and
 * [`TasksAdapter::watch_tasks`].
 */
export interface TaskFilter {
  status?: TaskStatus
  titleContains?: string
  createdAfterNs?: bigint
  createdBeforeNs?: bigint
  updatedAfterNs?: bigint
  updatedBeforeNs?: bigint
  orderBy?: TasksOrderBy
  limit?: number
}

/** Ordering for task queries. */
export declare const enum TasksOrderBy {
  IdAsc = 'IdAsc',
  IdDesc = 'IdDesc',
  CreatedAsc = 'CreatedAsc',
  CreatedDesc = 'CreatedDesc',
  UpdatedAsc = 'UpdatedAsc',
  UpdatedDesc = 'UpdatedDesc'
}

/** Task lifecycle status. */
export declare const enum TaskStatus {
  Pending = 'Pending',
  Completed = 'Completed'
}
